### PR TITLE
Update frame index to start at 0 instead of 1

### PR DESCRIPTION
**Pull request by lydia-at-amazon**
The start of frame index should be set to 0, not 1.

### CODE REVIEW

**Review by thirtytwobits — APPROVED** [review]

**Review by emrainey — APPROVED** [review]
Wow that was more involved than I thought and more deeply entrenched.

**Comment by lydia-at-amazon** [comment]
> Wow that was more involved than I thought and more deeply entrenched.

+1

**Comment by lydia-at-amazon** [comment]
Tested on-target and verified that I could send a 64,000 byte message:
```
Frame index: 0
Frame index: 1
Frame index: 2
Frame index: 3
Frame index: 4
Frame index: 5
Frame index: 6
Frame index: 7
Frame index: 8
Frame index: 9
Frame index: 10
Frame index: 11
Frame index: 12
Frame index: 13
Frame index: 14
Frame index: 15
Frame index: 16
Frame index: 17
Frame index: 18
Frame index: 19
Frame index: 20
Frame index: 21
Frame index: 22
Frame index: 23
Frame index: 24
Frame index: 25
Frame index: 26
Frame index: 27
Frame index: 28
Frame index: 29
Frame index: 30
Frame index: 31
Frame index: 32
Frame index: 33
Frame index: 34
Frame index: 35
Frame index: 36
Frame index: 37
Frame index: 38
Frame index: 39
Frame index: 40
Frame index: 41
Frame index: 42
Frame index: 43
Frame index: 44
Frame index: 45
Frame index: 2147483694
Listener - onBroadcast Subject: 100
Listener - remote node ID: 44
Size: 64000
Successfully validated 64000 byte message
```

**Comment by lydia-at-amazon** [comment]
Removed the changes related to redundant transports that are pending in this PR: https://github.com/OpenCyphal-Garage/libudpard/pull/23

Will go ahead and merge this change now

**Pull request merged**
